{{ if .Values.service.external }}
apiVersion: v1
kind: Service
metadata:
  annotations:
       service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  creationTimestamp: null
  labels:
    app: {{ template "cassandra.name" . }}
    chart: {{ template "cassandra.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "cassandra.fullname" . }}-external
  namespace: {{ .Release.Namespace }}
  selfLink: /api/v1/namespaces/cassandra/services/cassandra
spec:
  ports:
    {{- if .Values.exporter.enabled }}
  - name: exporter
    port: 5556
    protocol: TCP
    targetPort: {{ .Values.exporter.port }}
    {{- end }}
  - name: intra
    port: 7000
    protocol: TCP
    targetPort: 7000
  - name: tls
    port: 7001
    protocol: TCP
    targetPort: 7001
  - name: jmx
    port: 7199
    protocol: TCP
    targetPort: 7199
  - name: cql
    port: {{ default 9042 .Values.config.ports.cql }}
    protocol: TCP
    targetPort: {{ default 9042 .Values.config.ports.cql }}
  - name: thrift
    port: {{ default 9160 .Values.config.ports.thrift }}
    protocol: TCP
    targetPort: {{ default 9160 .Values.config.ports.thrift }}
  selector:
    app: {{ template "cassandra.name" . }}
    release: {{ .Release.Name }}
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
{{- end }}
